"""add session_events

Revision ID: a8f5275f46b7
Revises: 112047c88b48
Create Date: 2026-08-19 06:57:58.997382
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8f5275f46b7'
down_revision: Union[str, None] = '112047c88b48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('data', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'seq', name='uq_session_event_conv_seq')
    )
    with op.batch_alter_table('session_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_events_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_events_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_events_type'), ['type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_events_type'))
        batch_op.drop_index(batch_op.f('ix_session_events_id'))
        batch_op.drop_index(batch_op.f('ix_session_events_conversation_id'))

    op.drop_table('session_events')
    # ### end Alembic commands ###
